### ISSUE TITLE
Create checking conditions depending on the input data

### ISSUE THREAD

**Issue by acsenrafilho** [CSIM-Toolkits/LesionSimulatorExtension#2]
It should be interesting a previous input data checking in order to see if the registration step will be performed correctly.
Remove the restrictive adding of the T1 image.
Stop method if only DTI data is inserted.

**Comment by fsimozo** [comment]
Removed the need for T1 image.

Defined an order in which a structural modality will be accepted as the reference. At least one structural image modality is needed.
